/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Caixa;
import DAO.CaixaDAO;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author johnm
 */
public class FrmFecharCaixa extends javax.swing.JFrame {

    private Caixa caixa;
    public FrmFecharCaixa() {
        initComponents();
        lerDadosIniciais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtDeveria = new javax.swing.JTextField();
        txtTem = new javax.swing.JTextField();
        TxtSituacao = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fechar Caixa");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Valor que deveria estar no caixa: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Valor que está no caixa:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Situação");

        TxtDeveria.setBackground(new java.awt.Color(255, 255, 51));
        TxtDeveria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDeveriaActionPerformed(evt);
            }
        });

        txtTem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTemFocusLost(evt);
            }
        });

        TxtSituacao.setBackground(new java.awt.Color(255, 255, 51));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtSituacao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTem)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtDeveria, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
            .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtDeveria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnConfirmar)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDeveriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDeveriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDeveriaActionPerformed

    private void txtTemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTemFocusLost
        double tem = Double.parseDouble(this.txtTem.getText().trim().replace(",","."));
        double deveria = Double.parseDouble(this.TxtDeveria.getText().trim().replace(",", "."));
        double saldo = tem- deveria;
        if(saldo > 0.0){
            this.TxtSituacao.setText("Passou R$"+saldo);  
        } else if(saldo<-0.00000000){
            this.TxtSituacao.setText("Faltou R$"+saldo);
        }else{
            this.TxtSituacao.setText("Caixa Correto!");
        }
    }//GEN-LAST:event_txtTemFocusLost

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        double tem = Double.parseDouble(this.txtTem.getText().trim().replace(",","."));
        double deveria = Double.parseDouble(this.TxtDeveria.getText().trim().replace(",", "."));
        double saldo = tem- deveria;
        caixa.setDatafechamento(new Date());
        caixa.setValorfinal(tem);
        caixa.setDiferença(saldo);
        caixa.setAberto(0);
        CaixaDAO dao =  new CaixaDAO("svc","root");
        try {
            dao.fechaCaixa(caixa);
            JOptionPane.showMessageDialog(null, "Caixa Fechado com sucesso!");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FrmFecharCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDeveria;
    private javax.swing.JTextField TxtSituacao;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtTem;
    // End of variables declaration//GEN-END:variables

    private void lerDadosIniciais() {
        CaixaDAO dao = new CaixaDAO("svc","root");
        try {
            caixa = dao.lerCaixa();
            double valor = caixa.getValorinicial()+caixa.getVendas()+caixa.getSuprimentos()-
                    caixa.getDeposito();
            this.TxtDeveria.setText(valor+"");
                    
        } catch (SQLException ex) {
            Logger.getLogger(FrmFecharCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
