/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.CaixaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author johnm
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        lerDadosIniciais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuProdutos = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuVendedores = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuIniciarCaixa = new javax.swing.JMenuItem();
        menuFecharCaixa = new javax.swing.JMenuItem();
        menuDeposito = new javax.swing.JMenuItem();
        menuSuprimento = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuIniciarVenda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Comercial de Vendas");

        jMenu1.setText("Arquivos");

        menuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuProdutos.setText("Produtos");
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(menuProdutos);

        menuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuClientes);

        menuVendedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuVendedores.setText("Vendedores");
        menuVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendedoresActionPerformed(evt);
            }
        });
        jMenu1.add(menuVendedores);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Caixa");

        menuIniciarCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        menuIniciarCaixa.setText("Iniciar");
        menuIniciarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarCaixaActionPerformed(evt);
            }
        });
        jMenu2.add(menuIniciarCaixa);

        menuFecharCaixa.setText("Fechar");
        menuFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFecharCaixaActionPerformed(evt);
            }
        });
        jMenu2.add(menuFecharCaixa);

        menuDeposito.setText("Deposito");
        menuDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepositoActionPerformed(evt);
            }
        });
        jMenu2.add(menuDeposito);

        menuSuprimento.setText("Suprimento");
        menuSuprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuprimentoActionPerformed(evt);
            }
        });
        jMenu2.add(menuSuprimento);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Vendas");

        menuIniciarVenda.setText("Iniciar Venda");
        menuIniciarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarVendaActionPerformed(evt);
            }
        });
        jMenu4.add(menuIniciarVenda);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
   FrmProdutos frm = new FrmProdutos();
   frm.setVisible(true);
      
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void menuIniciarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarCaixaActionPerformed
       FrmIniciaCaixa frm = new FrmIniciaCaixa(this);
       frm.setVisible(true);
    }//GEN-LAST:event_menuIniciarCaixaActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
       FrmClientes frm  = new FrmClientes();
       frm.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendedoresActionPerformed
       FrmVendedor frm = new FrmVendedor();
       frm.setVisible(true);
    }//GEN-LAST:event_menuVendedoresActionPerformed

    private void menuDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepositoActionPerformed
     FrmDeposito frm = new FrmDeposito();
     frm.setVisible(true);
     
     
    }//GEN-LAST:event_menuDepositoActionPerformed

    private void menuSuprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuprimentoActionPerformed
        FrmSuprimentos frm = new FrmSuprimentos();
        frm.setVisible(true);
    }//GEN-LAST:event_menuSuprimentoActionPerformed

    private void menuFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFecharCaixaActionPerformed
      FrmFecharCaixa frm = new FrmFecharCaixa();
      frm.setVisible(true);
    }//GEN-LAST:event_menuFecharCaixaActionPerformed

    private void menuIniciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarVendaActionPerformed
      FrmIniciarVendas frm = new FrmIniciarVendas();
      frm.setVisible(true);
    }//GEN-LAST:event_menuIniciarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
        public void acessarMenuIniciarCaixa(boolean hablitar){
            this.menuIniciarCaixa.setEnabled(hablitar);
            
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuDeposito;
    private javax.swing.JMenuItem menuFecharCaixa;
    private javax.swing.JMenuItem menuIniciarCaixa;
    private javax.swing.JMenuItem menuIniciarVenda;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menuSuprimento;
    private javax.swing.JMenuItem menuVendedores;
    // End of variables declaration//GEN-END:variables

    private void lerDadosIniciais() {
        CaixaDAO dao = new CaixaDAO("svc","root");
        int quantidade;
        try {
            quantidade = dao.quantidadeCaixaAberto();
         if(quantidade == 0){
            this.menuIniciarCaixa.setEnabled(true);
        }else
            this.menuIniciarCaixa.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
}
